services:
  app:
    build: .
    network_mode: host
    volumes:
      - .:/app
    env_file:
      - env/.db
    working_dir: /app

  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    volumes:
      - .:/app
    env_file:
      - env/.db
    working_dir: /app
    networks:
      - activitygen

  nginx:
    image: nginx:alpine
    ports:
      - "${ACTIVITYGEN_WEB_PORT:-8080}:80"
    volumes:
      - .:/app
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
    networks:
      - activitygen

networks:
  activitygen:
    driver: bridge
